### ISSUE TITLE
Support "CASE expr WHEN value ..." case statements

### ISSUE THREAD

**Issue by johansjob** [alanmcruickshank/sqlfluff#359]
**Problem**
BigQuery (and many other DBs?) support two types of case statements.
https://cloud.google.com/bigquery/docs/reference/standard-sql/conditional_expressions

```
CASE expr
  WHEN value THEN result
  [WHEN ...]
  [ELSE else_result]
  END
```
and
```
CASE
  WHEN cond1 THEN result
  [WHEN cond2...]
  [ELSE else_result]
  END
```
Currently sqlfluff only support the later. 

**Example**
Shows both type of case statements, the nbr_weekday1 does not parse.
```
with abc as (
    select 1 as cnt, 'weeknight' as label
    union all
    select 1 as cnt, 'weeknight' as label
    union all
    select 1 as cnt, 'weekday' as label
)

select
    sum(case label when 'weekday' then cnt end) as nbr_weekday1
    , sum(case when label = 'weekday' then cnt end) as nbr_weekday2
from abc
```

**Expected**
Both case statements parse successfully :)

**Settings**
Version: 0.3.4
Dialect: BigQuery

**Comment by alanmcruickshank** [comment]
Agreed.

That syntax is supported in:
- mysql: https://dev.mysql.com/doc/refman/5.7/en/case.html
- postgres: https://www.postgresql.org/docs/7.4/functions-conditional.html
- snowflake: https://docs.snowflake.com/en/sql-reference/functions/case.html

This should be an easy one to add for anyone keen to get a first PR in the parser section of the codebase. Otherwise I'll hoover it up next time I'm doing a load of parser improvements.
