### ISSUE TITLE
SQLFluff does not understand some BIGQUERY timestamp keywords

### ISSUE THREAD

**Issue by ericxiao251** [alanmcruickshank/sqlfluff#387]
```sql
WHERE dd.datetime >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 2 YEAR), year)
```

Something like this, it does not understand the `YEAR` date `part`.

reference to the possible date parts: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#extract

<img width="489" alt="Screen Shot 2020-06-18 at 11 15 09 PM" src="https://user-images.githubusercontent.com/9758510/85093213-9845d180-b1b9-11ea-8c1c-5a4b8ec77ca0.png">

**Comment by ericxiao251** [comment]
Another example is that it does not understand the keyword `DATE`.

```sql
SELECT
  gmv._merchant_key,
  gmv.order_created_at,
  EXTRACT(DATE FROM gmv.order_created_at) AS order_dt
FROM ... as gmv
LIMIT 1
```

**Comment by alanmcruickshank** [comment]
I think I agree with your diagnosis. Thanks for looking into this. 👍

**Comment by alanmcruickshank** [comment]
@ericxiao251 - would you mind reviewing the pull request to fix this? https://github.com/alanmcruickshank/sqlfluff/pull/443

**Comment by tunetheweb** [comment]
@ericxiao251 not sure if you still recall this, but this is causing issues due to some recent changes in SQLFluff and wanted to check this one with you again:

> Another example is that it does not understand the keyword `DATE`.
> 
> ```sql
> SELECT
>   gmv._merchant_key,
>   gmv.order_created_at,
>   EXTRACT(DATE FROM gmv.order_created_at) AS order_dt
> FROM ... as gmv
> LIMIT 1
> ```
> 
> I believe we just need to update this list here: https://github.com/alanmcruickshank/sqlfluff/blob/master/src/sqlfluff/dialects/dialect_bigquery.py#L32-L33 with values from here: https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#extract

`EXTRACT(DATE FROM gmv.order_created_at) AS order_dt` is not value BigQuery and I get this:

![image](https://user-images.githubusercontent.com/10931297/148965599-9d96ed06-963f-479e-a7b6-38f318709f63.png)

Also https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#extract doesn't have DATE, DATETIME nor TIME listed there. Not sure if that changed since this issue? Anyway planning on removing this in #2283 so wanted to double check in case you had any more info on that?
