### ISSUE TITLE
Output for subdirectories and files should be in alphabetical order

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#75]
When reviewing output for a large directory structure, I noticed that the files are processed in an sequence that jumps across directories. It would be cool to process in alphabetical order (and depth first, I think?).

Example output (with the actual lint warnings removed, leaving just the filenames):
 
== [sql/benchmark_summary_queries/constraints/_postcondition_no_nulls.sql] FAIL
== [sql/audience_size_queries/constraints/_postcondition_check_gdpr_compliance.sql] FAIL
== [sql/benchmark_summary_queries/constraints/_postcondition_anonymized_buckets.sql] FAIL

Notice a file from `sql/audience_size_queries/` appears in between the output for two files in the same directory, `sql/benchmark_summary_queries/`.

**Comment by alanmcruickshank** [comment]
Great idea. This also should be fairly straightforward to implement. All the translation from an ambiguous path into a set of filenames in in the `paths_from_path` method in the `Linter` class. I'm not surprised the ordering is a bit messed up because at the moment it uses python sets under the hood. I think I originally used the `set` object do do any potential deduping, but I'm not sure that's actually necessary.

You can see the method here:
https://github.com/alanmcruickshank/sqlfluff/blob/ce83fac670bd19f3bf4992cc9b8960c73bf12a33/src/sqlfluff/linter.py#L541

If we wanted to sort it in a particular way before returning, so long as we return an iterable of some kind (a `list` would be fine), then I think that could work. Bonus points if we avoid sorting and just use the `os.walk` method wisely to get it to return the files in a sensible order from the get go.

@barrywhart, fancy having a go at doing this one yourself and submitting a PR?

**Comment by barrywhart** [comment]
Sure, I'll give it a try.

**Comment by barrywhart** [comment]
I fixed it and opened a PR: #81
